---
title: "try-catch-finally (C# Reference)"
ms.custom: na
ms.date: "09/22/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: na
ms.suite: na
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: na
ms.topic: "article"
f1_keywords: 
  - "catch-finally_CSharpKeyword"
  - "catch-finally"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "finally blocks [C#]"
  - "try-catch statement [C#]"
ms.assetid: a1b443b0-ff7a-43ab-b835-0cc9bfbd15ca
caps.latest.revision: 25
translation.priority.ht: 
  - "de-de"
  - "ja-jp"
---
# try-catch-finally (C# Reference)
A common usage of `catch` and `finally` together is to obtain and use resources in a `try` block, deal with exceptional circumstances in a `catch` block, and release the resources in the `finally` block.  
  
 For more information and examples on re-throwing exceptions, see [try-catch](../VS_csharp/try-catch--csharp-reference-.md) and [Throwing Exceptions](assetId:///72bdd157-caa9-4478-9ee3-cb4500b84528). For more information about the `finally` block, see [try-finally](../VS_csharp/try-finally--csharp-reference-.md).  
  
## Example  
 [!code[csrefKeywordsExceptions#1](../VS_csharp/codesnippet/CSharp/try-catch-finally--csharp-reference-_1.cs)]  
  
## C# Language Specification  
 [!INCLUDE[CSharplangspec](../VS_csharp/includes/csharplangspec_md.md)]  
  
## See Also  
 [C# Reference](../VS_csharp/csharp-reference.md)   
 [C# Programming Guide](../VS_csharp/csharp-programming-guide.md)   
 [C# Keywords](../VS_csharp/csharp-keywords.md)   
 [try, throw, and catch Statements (C++)](../VS_csharp/try--throw--and-catch-statements--c---.md)   
 [Exception Handling Statements](../VS_csharp/exception-handling-statements--csharp-reference-.md)   
 [throw](../VS_csharp/throw--csharp-reference-.md)   
 [Throwing Exceptions](assetId:///72bdd157-caa9-4478-9ee3-cb4500b84528)   
 [using Statement (C# Reference)](../VS_csharp/using-statement--csharp-reference-.md)